version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgresql 
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: postgre_db 
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
